2025-01-15 14:14:16,746 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Nikolay\Desktop\urban-university\Study_Python\Module_12\module_12_04\tests_12_4.py", line 24, in test_run
    runner = Runner(222, 5)
             ^^^^^^^^^^^^^^
  File "C:\Users\Nikolay\Desktop\urban-university\Study_Python\Module_12\module_12_04\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-15 14:14:16,747 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Nikolay\Desktop\urban-university\Study_Python\Module_12\module_12_04\tests_12_4.py", line 14, in test_walk
    walker = Runner('Walker', -1)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikolay\Desktop\urban-university\Study_Python\Module_12\module_12_04\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
